# Generated by Django 4.0.2 on 2022-03-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcaucouapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sudoku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_sudoku', models.TextField()),
                ('end_sudoku', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
