# Generated by Django 4.0.2 on 2022-03-26 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcaucouapp', '0005_usertogroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertogroup',
            old_name='id_group',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='usertogroup',
            old_name='id_user',
            new_name='user',
        ),
    ]
