# Generated by Django 4.0.2 on 2022-03-26 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcaucouapp', '0002_sudoku'),
        ('arcaucouapp', '0005_usertogroup'),
    ]

    operations = [
    ]
