# Generated by Django 4.0.2 on 2022-03-27 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arcaucouapp', '0006_merge_0002_sudoku_0005_usertogroup'),
        ('arcaucouapp', '0006_rename_id_group_usertogroup_group_and_more'),
    ]

    operations = [
    ]
