# Generated by Django 4.0.2 on 2022-04-01 16:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arcaucouapp', '0008_rename_id_user_leaderboard_user_alter_group_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leaderboard',
            unique_together={('user', 'date')},
        ),
    ]
